# Generated by Django 2.2.2 on 2019-07-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=30, verbose_name='Friend')),
                ('Student', models.ManyToManyField(to='home.Student')),
            ],
        ),
    ]
