# Generated by Django 2.2.2 on 2019-07-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_friends_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='friends',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Teacher'),
        ),
    ]
