# Generated by Django 2.2.2 on 2019-07-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190702_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='Student',
        ),
    ]
