# Generated by Django 2.2.2 on 2019-07-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190702_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='stu',
        ),
        migrations.AddField(
            model_name='parents',
            name='son',
            field=models.ManyToManyField(null=True, to='home.Student'),
        ),
    ]
